#!/bin/bash
# 你的自定义命令
echo "Running custom startup script on first boot"

# 设置docker的目录
sed -i 's|/mnt/sda4/docker/|/mnt/mmcblk2p4/docker/|g' /etc/config/dockerd

# 设置防火墙去掉有WAN导致报错的数据
sed -i '/config forwarding .vpntowan./,/option dest .wan./d' /etc/config/firewall

# 清空socat残留配置
echo -n > /etc/config/socat
rm /etc/config/socat-opkg


# 这个脚本会在成功运行后自动被删除
exit 0
